### ISSUE TITLE
Version 0.3.0 does not draw meshscatter() in Pluto

### ISSUE THREAD

**Issue by woolstar** [JuliaPlots/WGLMakie.jl#79] opened 2021-01-12 03:44 UTC
Created
https://github.com/woolstar/test/blob/master/julia/test_webgl.jl

previously to figure out with my graphics card load was so high, but currently does not draw at all after updating to 0.3.0

From the notebook:

	U= rand( -1.:.001:1, 3, 1000 )
	pts= Point3.(U[:,i] for i ∈ 1:size(U,2))
	
	scene= Scene()
	meshscatter!( scene, pts, markersize= 0.02, color=:red )

**Comment by SimonDanisch** [comment] 2021-01-12 16:43
duplicate of https://github.com/JuliaPlots/Makie.jl/issues/811

**Closed as completed by SimonDanisch** 2021-01-12 16:43 UTC
